"use client";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
export const metadata = {
  title: "Trello 2.0 clone",
  description: "Generated by Hukum from Tutorial",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#F5F6F8]">
        <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLEAUTH_ID!}>
          {children}
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
